import type { Metadata } from "next";
import "./globals.css";
import { space_grotesk } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space_grotesk.className} flex min-h-svh flex-col antialiased`}
      >
        <nav className="bg-slate-800/50 px-10 py-6">
          <div className="h-4 w-32 rounded bg-slate-400/80"></div>
        </nav>
        <div className="sm mx-auto my-16 max-w-6xl flex-1 px-4 sm:px-8 md:px-12">
          {children}
        </div>
        <div className="bg-slate-800/50 px-10 pb-8 pt-14">
          <div className="h-4 w-32 rounded bg-slate-400/80"></div>
          <div className="mt-2 h-4 w-16 rounded bg-slate-400/80"></div>
          <div className="mt-2 h-4 w-20 rounded bg-slate-400/80"></div>
        </div>
      </body>
    </html>
  );
}
